// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packet.proto

module packet;

import google.protobuf;

enum protocVersion = 3014000;

class Message
{
    @Proto(1) string publicKey = protoDefaultValue!string;
    @Proto(2) string signature = protoDefaultValue!string;
    @Proto(3) MessageType type = protoDefaultValue!MessageType;
    @Proto(4) bytes payload = protoDefaultValue!bytes;
}

enum MessageType
{
    SESSION = 0,
    ADVERTISEMENT = 1,
}
