// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: advertisement.proto

module advertisement;

import google.protobuf;

enum protocVersion = 3014000;

class AdvertisementMessage
{
    @Proto(1) RouteEntry[] routes = protoDefaultValue!(RouteEntry[]);
}

class RouteEntry
{
    @Proto(1) string address = protoDefaultValue!string;
}
