// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobufs/advertisement.proto

module advertisement;

import google.protobuf;

enum protocVersion = 3014000;

class AdvertisementMessage
{
    @Proto(1) string r2rPort = protoDefaultValue!string;
    @Proto(2) RouteEntry[] routes = protoDefaultValue!(RouteEntry[]);
}

class RouteEntry
{
    @Proto(1) string address = protoDefaultValue!string;
}
