// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: source/libsweatyballs/link/message/types/protobufs/advertisement.proto

module advertisement;

import google.protobuf;

enum protocVersion = 3014000;
