// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: source/libsweatyballs/link/message/types/protobufs/packet.proto

module packet;

import google.protobuf;

enum protocVersion = 3014000;

class Message
{
    @Proto(1) string publicKey = protoDefaultValue!string;
    @Proto(2) string signature = protoDefaultValue!string;
    @Proto(3) uint neighborPort = protoDefaultValue!uint;
    @Proto(4) MessageType type = protoDefaultValue!MessageType;
    @Proto(5) bytes payload = protoDefaultValue!bytes;
}

enum MessageType
{
    SESSION = 0,
    ADVERTISEMENT = 1,
}
